source "https://rubygems.org"
gemspec
gem "webrick", "~> 1.8"
gem "jekyll-coffeescript"
gem "jekyll-default-layout"
gem "jekyll-github-metadata"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-titles-from-headings"
gem "jekyll-relative-links"